print('🧹 GUIA PARA APAGAR TODOS OS PRODUTOS WOOCOMMERCE')
print('=' * 60)
print()

print('🚨 ATENÇÃO: ISSO APAGARÁ TODOS OS 3876 PRODUTOS!')
print('📋 MAS É A MELHOR SOLUÇÃO PARA LIMPEZA COMPLETA')
print()

print('🔧 MÉTODO 1 - VIA WORDPRESS (RECOMENDADO):')
print('1. Acesse: seu-site.com.br/wp-admin')
print('2. Vá para: WooCommerce → Produtos')
print('3. Marque: "Selecionar todos" (primeiro checkbox)')
print('4. No menu "Ações em massa", escolha: "Mover para lixeira"')
print('5. Clique em: "Aplicar"')
print('6. Vá para: Lixeira → Esvaziar lixeira')
print('7. Confirme: "Esvaziar permanentemente"')
print()

print('🔧 MÉTODO 2 - VIA PHPMYADMIN (AVANÇADO):')
print('1. Acesse: cPanel → phpMyAdmin')
print('2. Selecione: banco de dados WordPress')
print('3. Execute estes SQLs:')
print('   DELETE FROM wp_posts WHERE post_type = "product";')
print('   DELETE FROM wp_postmeta WHERE post_id NOT IN (SELECT id FROM wp_posts);')
print('4. Limpe cache: wp_options WHERE option_name LIKE "woocommerce_%";')
print()

print('🔧 MÉTODO 3 - VIA PLUGIN:')
print('1. Instale plugin: "Bulk Delete" ou "WooCommerce Product Delete"')
print('2. Configure para apagar todos os produtos')
print('3. Execute limpeza completa')
print()

print('🎯 APÓS APAGAR TUDO:')
print('✅ Terá 0 produtos no WooCommerce')
print('✅ Poderá importar planilha limpa')
print('✅ Terá exatamente 969 produtos')
print('✅ Zero duplicatas')
print('✅ Catálogo perfeito')
print()

print('🚀 PRÓXIMOS PASSOS:')
print('1. APAGUE todos os 3876 produtos')
print('2. VERIFIQUE que ficou 0 produtos')
print('3. IMPORTE planilha corrigida')
print('4. RESULTADO: 969 produtos perfeitos')
print()

print('⚠️ IMPORTANTE:')
print('- Faça backup antes de apagar')
print('- Depois de apagar, esvazie lixeira')
print('- Importe apenas uma vez')
print('- Use IDs corretos da planilha')
print()

print('📞 SE PRECISAR DE AJUDA:')
print('- Me chame durante o processo')
print('- Posso ajudar com cada método')
print('- Garanto sucesso na operação')
